### ISSUE TITLE
Wechat Dev Notes

### ISSUE THREAD

**Issue by leoyoung07** [leoyoung07/blog#30]
*记录微信（公众号/网页/小程序）开发中的一些坑和填坑方法*

## 关于网页字体缩放

微信中允许用户调整网页字体大小，而当页面使用rem作为单位进行布局时，用户调整字体大小就会导致页面布局变乱。

- Android解决方法

```JavaScript
/*
 * 页面加入这段代码可使Android机器页面不再受到用户字体缩放强制改变大小
 * 但是会有一个1秒左右的延迟，期间可以考虑通过loading展示
 * 仅供参考
 */
(function(){
  if (typeof WeixinJSBridge === 'undefined') {
    document.addEventListener('WeixinJSBridgeReady', function (e) {
      setTimeout(function(){
        WeixinJSBridge.invoke('setFontSizeCallback',{'fontSize':0}, function(res) {
          // alert(JSON.stringify(res));
        });
      },0);
    });
  } else {
    setTimeout(function(){
      WeixinJSBridge.invoke('setFontSizeCallback',{'fontSize':0}, function(res) {
        // alert(JSON.stringify(res));
      });
    },0);
  }
})();
```

- iOS解决方法

```CSS
body {
  -webkit-text-size-adjust: 100% !important;
  text-size-adjust: 100% !important;
  -moz-text-size-adjust: 100% !important;
}
```

### 参考

- [【知识整理】移动端微信页面禁止字体放大 - CSDN博客](http://blog.csdn.net/qq_19891827/article/details/51275080)
